#logging:
#  level:
#    az.ingress.lombokandlogging.service: trace

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres

#  not appear null fields in json
#  jackson:
#    default-property-inclusion: non_null

#  default-property
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml